### PR TITLE
Dropdown menu

### PR DESCRIPTION
**Pull request by FormalSnake**
I have added a dropdown menu because I need one and it might come in handy for future users of this framework.
Feel free to help me with this because my swift skills are not that good yet.

https://github.com/MrKai77/Luminare/assets/90651091/7db8baf0-ae86-4342-927e-abc685b46c2c

For example this only works properly in sections.
Maybe its best to add this into a dev branch of some sort for now.

Also, the tuist files have pushed with this commit for some reason.

### CODE REVIEW

**Comment by MrKai77** [comment]
Sorry, but a dropdown menu should be shown in a popup in my opinion, and should not move content below it. 

In addition, when Jace sent this in the Arc Discord server, you explicitly stated that this method is not capable of handling many items.
image

An ideal dropdown menu should be able to handle many items without any sort of lag :)

p.s:
> Maybe its best to add this into a dev branch of some sort for now.

Just letting you know that the dev branch is essentially your fork!

**Comment by FormalSnake** [comment]
I didnt mean it was not capable I just do not know how to put 195 items in it in swift.

I have tried to make it a popup but I cannot get that to work at all, ive tried NSPanel and the Popover but that doesnt really work.

**Comment by MrKai77** [comment]
> I didnt mean it was not capable I just do not know how to put 195 items in it in swift.

Ah.. use a `for` loop!

> I have tried to make it a popup but I cannot get that to work at all, ive tried NSPanel and the Popover but that doesnt really work.

Do you know why it doesn't work?

**Comment by FormalSnake** [comment]
It really makes the layout all weird and stuff and aligning it is hard

**Comment by MrKai77** [comment]
I would suggest that you look into why that's happening?

**Comment by FormalSnake** [comment]
I really want help with this dropdown menu, ive been looking into it for so long and I cannot get it to work well.

**Pull request closed without merging**
