### PR TITLE
✨ Initialize Views Like SwiftUI

### PR DESCRIPTION
**Pull request by KrLite**
- Convenience initializers that works more like the SwiftUI ones (breaking changes).
- Some method signature updates (breaking changes).
- A `StringFormatStyle` to help utilize `LuminareTextField` **(tests required).**

### CODE REVIEW

**Comment by MrKai77** [comment]
Hey @KrLite! Sorry for the late response, but I will be taking a look at this after #11 is merged!
If any merge conflicts come up, I'll take care of them, so no worries :)

**Review by SenpaiHunters — APPROVED** [review]
Looks good, didn't take us 6 months to push...

**Review by MrKai77 — APPROVED** [review]
Looks good! Thank you, and sorry for the late review 😓

**Comment by KrLite** [comment]
> Looks good! Thank you, and sorry for the late review 😓

No problem! I'm happy to contribute to **Luminare** as I'm using it practically in my other projects too.

**Pull request merged**
